### ISSUE TITLE
[suggestion] Deploy PDF through CI

### ISSUE THREAD

**Issue by briochemc** [introocean/introocean-en#2]
Just a suggestion. This repo is great but I think it could benefit from having a button to download the PDF in the readme (without the PDF itself being version-controlled, just the LaTeX). I have not done this myself, but I think this could be done by following, e.g., [HowTo-Deploy-LaTeX-Documents](https://github.com/SimonWaldherr/HowTo-Deploy-LaTeX-Documents). 

---

**EDIT**: I just realized the PDFs are available through releases. So CI could simply automate that process. And having the badge/button on the readme is still a suggestion 🙂

**Comment by koldunovn** [comment]
Thanks a lot for the suggestion, it certainly makes sense to do so, and thank you for the link! We now have the badge with a link to releases.
